version: '3.4'

services:
  discord.client:
    depends_on:
      - postgres.db
      - eventstore.db
    # points to the root of this repository
    build: ../../.
    restart: unless-stopped
    env_file:
      - .discord.env
    environment:
      - ESDB_URL=esdb://eventstore.db:2113?tls=false
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_URL=postgresql://root:password@postgres.db:5432/readmodel
      - LOGGING_LEVEL=debug

  postgres.db:
    image: postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
    volumes:
      - type: volume
        source: postgres-volume-data
        target: /var/lib/postgresql/data
      - ../postgres-init:/docker-entrypoint-initdb.d

  eventstore.db:
    image: eventstore/eventstore:latest
    restart: unless-stopped
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_RUN_PROJECTIONS=All
    ports:
      - '1114:1113'
      - '2114:2113'
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  postgres-volume-data:
